# -*- coding: utf-8 -*-
"""FRaud - Detection Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5scBT4F6C59tBWuENpfBMA6vny5-Osv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (classification_report, confusion_matrix,
                             roc_auc_score, roc_curve, ConfusionMatrixDisplay)

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("fraud.csv")

print("=" * 50)
print(f"Dataset Shape: {df.shape}")
print("=" * 50)

print("\n📌 First 5 rows:")
print(df.head())

print("\n📌 Data Types:")
print(df.dtypes)

print("\n📌 Basic Statistics:")
print(df.describe())

print("\n📌 Missing Values:")
print(df.isnull().sum())

print("\n📌 Target Column Class Distribution:")
print(df["is_fraud"].value_counts())
print(df["is_fraud"].value_counts(normalize=True).round(3))

binary_cols = ["is_weekend", "is_first_transaction", "store_type", "device_type"]
continuous_cols = [
    "transaction_amount", "hour_of_day", "num_items",
    "customer_age", "prev_transactions", "distance_from_home",
    "network_quality", "velocity_score"
]

for col in binary_cols:
    mode_val = df[col].mode()[0]
    df[col].fillna(mode_val, inplace=True)

for col in continuous_cols:
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)

print("✅ Missing values handled.")
print("Remaining nulls:", df.isnull().sum().sum())

print("No columns dropped — all features are relevant for fraud detection.")
print("TARGET COLUMN: is_fraud")
print("   → 0 = Legitimate transaction")
print("   → 1 = Fraudulent transaction")

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
df["is_fraud"].value_counts().plot(kind="bar", ax=axes[0], color=["steelblue", "tomato"])
axes[0].set_title("Class Distribution (0=Legit, 1=Fraud)")
axes[0].set_xlabel("is_fraud")
axes[0].set_ylabel("Count")
axes[0].tick_params(rotation=0)
df.groupby("is_fraud")["transaction_amount"].plot(kind="kde", ax=axes[1], legend=True)
axes[1].set_title("Transaction Amount by Fraud Label")
axes[1].set_xlabel("Transaction Amount")

plt.tight_layout()
plt.savefig("eda_plots.png", dpi=100)
plt.show()

df["amount_per_distance"] = df["transaction_amount"] / (df["distance_from_home"] + 1)
df["low_history_flag"] = (df["prev_transactions"] <= 1).astype(int)

print(" Feature engineering done.")
print("   → New feature: amount_per_distance")
print("   → New feature: low_history_flag")

TARGET = "is_fraud"
FEATURES = [col for col in df.columns if col != TARGET]

X = df[FEATURES]
y = df[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

cols_to_scale = [
    "transaction_amount", "hour_of_day", "num_items", "customer_age",
    "prev_transactions", "distance_from_home", "network_quality",
    "velocity_score", "amount_per_distance"
]

scaler = StandardScaler()

X_train[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])
X_test[cols_to_scale]  = scaler.transform(X_test[cols_to_scale])

print("✅ StandardScaler applied on continuous columns only.")
print("   → Fit on TRAIN only (no data leakage).")

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print(f" SMOTE applied.")
print(f"   Before: {y_train.value_counts().to_dict()}")
print(f"   After:  {pd.Series(y_train_resampled).value_counts().to_dict()}")

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest":       RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
    "Gradient Boosting":   GradientBoostingClassifier(n_estimators=100, random_state=42),
    "XGBoost":             XGBClassifier(n_estimators=100, random_state=42,
                                         eval_metric="logloss", verbosity=0)
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print("\n Cross-Validation ROC-AUC Scores (5-Fold):")
print("-" * 45)

cv_results = {}
for name, model in models.items():
    scores = cross_val_score(
        model, X_train_resampled, y_train_resampled,
        cv=cv, scoring="roc_auc", n_jobs=-1
    )
    cv_results[name] = scores
    print(f"{name:<25} → Mean AUC: {scores.mean():.4f} ± {scores.std():.4f}")

best_model_name = max(cv_results, key=lambda k: cv_results[k].mean())
best_model = models[best_model_name]

print(f"\n Best Model Selected: {best_model_name}")
print("   Reason: Highest cross-validated ROC-AUC with stable std (low overfitting risk).")


best_model.fit(X_train_resampled, y_train_resampled)


y_pred  = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

print("\n Classification Report on Test Set:")
print(classification_report(y_test, y_pred, target_names=["Legit", "Fraud"]))

auc_score = roc_auc_score(y_test, y_proba)
print(f"ROC-AUC Score on Test Set: {auc_score:.4f}")

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Legit", "Fraud"])
disp.plot(ax=axes[0], colorbar=False, cmap="Blues")
axes[0].set_title(f"Confusion Matrix — {best_model_name}")


fpr, tpr, _ = roc_curve(y_test, y_proba)
axes[1].plot(fpr, tpr, color="darkorange", lw=2, label=f"AUC = {auc_score:.4f}")
axes[1].plot([0, 1], [0, 1], color="navy", lw=1, linestyle="--")
axes[1].set_xlabel("False Positive Rate")
axes[1].set_ylabel("True Positive Rate")
axes[1].set_title(f"ROC Curve — {best_model_name}")
axes[1].legend(loc="lower right")

plt.tight_layout()
plt.savefig("model_results.png", dpi=100)
plt.show()
print("✅ Model evaluation plots saved as model_results.png")

if hasattr(best_model, "feature_importances_"):
    importances = pd.Series(best_model.feature_importances_, index=FEATURES)
    importances = importances.sort_values(ascending=False)

    plt.figure(figsize=(10, 5))
    importances.plot(kind="bar", color="steelblue")
    plt.title(f"Feature Importances — {best_model_name}")
    plt.ylabel("Importance Score")
    plt.tight_layout()
    plt.savefig("feature_importance.png", dpi=100)
    plt.show()
    print(" Feature importance plot saved as feature_importance.png")
else:
    print("ℹ  Feature importance not available for this model type.")

print("\n" + "=" * 55)
print(" PIPELINE SUMMARY")
print("=" * 55)
print(f"  Dataset shape          : {df.shape}")
print(f"  Target column          : is_fraud (0=Legit, 1=Fraud)")
print(f"  Class balance          : ~90% Legit / ~10% Fraud")
print(f"  Missing values handled : Median (continuous) / Mode (categorical)")
print(f"  Scaling                : StandardScaler on continuous cols only")
print(f"  Imbalance fix          : SMOTE on training set only")
print(f"  Feature engineering    : amount_per_distance, low_history_flag")
print(f"  Best model             : {best_model_name}")
print(f"  Final Test ROC-AUC     : {auc_score:.4f}")
print("=" * 55)

! pip install streamlit

!pip install streamlit imbalanced-learn pyngrok -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile fraud_app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.metrics import roc_auc_score, ConfusionMatrixDisplay, confusion_matrix
# from imblearn.over_sampling import SMOTE
# import warnings
# warnings.filterwarnings("ignore")
# 
# st.title("Fraud Detector")
# 
# # ── 1. Upload ──────────────────────────────────────────────
# st.header("1. Upload Data")
# file = st.file_uploader("Upload CSV")
# if not file:
#     st.stop()
# df = pd.read_csv(file)
# st.write(df.head())
# 
# # ── 2. Summary ─────────────────────────────────────────────
# st.header("2. Summary")
# st.write(f"Rows: {len(df)} | Fraud: {df['is_fraud'].sum()} | Legit: {(df['is_fraud']==0).sum()} | Nulls: {df.isnull().sum().sum()}")
# 
# # ── 3. Preprocessing ───────────────────────────────────────
# st.header("3. Preprocessing")
# for col in ['is_weekend','is_first_transaction','store_type','device_type']:
#     df[col] = df[col].fillna(df[col].mode()[0])
# for col in ['transaction_amount','hour_of_day','num_items','customer_age',
#             'prev_transactions','distance_from_home','network_quality','velocity_score']:
#     df[col] = df[col].fillna(df[col].median())
# df = df[df['transaction_amount'] > 5].copy()
# df['amount_per_distance'] = df['transaction_amount'] / (df['distance_from_home'] + 1)
# df['low_history_flag']    = (df['prev_transactions'] <= 1).astype(int)
# st.success(f"Done! Nulls: {df.isnull().sum().sum()} | Rows: {len(df)}")
# 
# # ── 4. Train ───────────────────────────────────────────────
# st.header("4. Train Model")
# X = df.drop(columns=['is_fraud']).select_dtypes('number')
# y = df['is_fraud']
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
# scaler = StandardScaler()
# X_train = pd.DataFrame(scaler.fit_transform(X_train), columns=X.columns)
# X_test  = pd.DataFrame(scaler.transform(X_test),      columns=X.columns)
# X_train, y_train = SMOTE(random_state=42).fit_resample(X_train, y_train)
# model = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
# model.fit(X_train, y_train)
# st.success("Model trained!")
# 
# # ── 5. Results ─────────────────────────────────────────────
# st.header("5. Results")
# y_pred = model.predict(X_test)
# auc    = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
# st.metric("ROC-AUC", f"{auc:.4f}")
# fig, axes = plt.subplots(1, 2, figsize=(10, 4))
# ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred), display_labels=["Legit","Fraud"]).plot(ax=axes[0], colorbar=False)
# pd.Series(model.feature_importances_, index=X.columns).sort_values().tail(8).plot(kind="barh", ax=axes[1])
# axes[1].set_title("Top Features")
# plt.tight_layout()
# st.pyplot(fig)
# plt.close()
# 
# # ── 6. Try It Yourself ─────────────────────────────────────
# st.header("6. Try It Yourself")
# with st.form("predict"):
#     cols = st.columns(3)
#     inputs = {col: cols[i % 3].number_input(col, value=float(df[col].median())) for i, col in enumerate(X.columns)}
#     if st.form_submit_button("Predict"):
#         row  = pd.DataFrame([inputs])
#         row  = pd.DataFrame(scaler.transform(row), columns=X.columns)
#         pred = model.predict(row)[0]
#         prob = model.predict_proba(row)[0][1]
#         if pred == 1:
#             st.error(f"🚨 FRAUD — {prob:.0%} confidence")
#         else:
#             st.success(f"✅ LEGIT — {1-prob:.0%} confidence")

from pyngrok import ngrok
import subprocess, threading, time

ngrok.set_auth_token("3DEZVWgyVVARBX4T5MOEM4nZIMJ_6NagbeB5KrEmpjk9DX8Dy")

threading.Thread(target=lambda: subprocess.run(['streamlit', 'run', 'fraud_app.py', '--server.port=8501']), daemon=True).start()
time.sleep(3)
print(ngrok.connect(8501))

# Cell 3 — Run the app and get the link
from pyngrok import ngrok
import subprocess, threading, time

ngrok.set_auth_token("3DEZVWgyVVARBX4T5MOEM4nZIMJ_6NagbeB5KrEmpjk9DX8Dy")

threading.Thread(target=lambda: subprocess.run(['streamlit', 'run', 'fraud_app.py', '--server.port=8501']), daemon=True).start()
time.sleep(3)

url = ngrok.connect(8501)
print('Open this link:', url)































